CREATE DATABASE LAPTOP
GO 
USE LAPTOP
GO
CREATE TABLE SANPHAM(
	ID int identity(1,1) NOT NULL,
	IDNoiSanXuat int NOT NULL,
	IDDongSanPham int NOT NULL,
	TenSanPham NVARCHAR(255) NOT NULL,
	AnhSanPham NVARCHAR(255) NULL,
	GiaSanPham int NOT NULL,
	SoLuong int NULL,
	MoTa text NULL,
	BaoHanh NVARCHAR(255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE TABLE NOISANXUAT(
ID INT IDENTITY (1,1) NOT NULL,
TenNoiSanXuat NVARCHAR(255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE KHUYENMAI(
ID INT IDENTITY(1,1) NOT NULL,
IDSanPam INT NULL,
IDPhuKien INT NULL,
GiaKhuyenMai int NULL,
NgayBatDauKhuenMai date NULL,
NgayKetThucKhuyenMai date NULL
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE DANHMUCSANPHAM(
ID INT IDENTITY(1,1) NOT NULL,
TenDanhMuc NVARCHAR(255) NOT NULL
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE DONGSANPHAM(
ID INT IDENTITY(1,1) NOT NULL,
IDDanhMuc INT NOT NULL,
TenSanPham NVARCHAR(255) NOT NULL
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO 
GO
CREATE TABLE LOAIPHUKIEN(
ID INT IDENTITY(1,1) NOT NULL,
IDDanhMuc INT NOT NULL,
TenPhuKien NVARCHAR(255) NOT NULL
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO 
CREATE TABLE PHUKIEN(
ID INT IDENTITY(1,1) NOT NULL,
IDLoaiPhuKien INT NOT NULL,
TenPhuKien NVARCHAR(255)NOT NULL,
AnhMau NVARCHAR(255) NULL,
Gia INT NULL,
SoLuong INT NULL,
MoTa text NULL,
BaoHanh NVARCHAR(255) NULL
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE  TABLE BINHLUAN(
ID INT IDENTITY(1,1) NOT NULL,
IDSanPham INT NOT NULL,
IDPhuKien INT NOT NULL,
HoTen NVARCHAR(255) NOT NULL,
NgayGio datetime NOT NULL,
NoiDung text NULL
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE KHACHHANG(
ID INT IDENTITY(1,1) NOT NULL,
HoVaTen NVARCHAR(255) NOT NULL,
SoDienThoai int NOT NULL,
Email NVARCHAR(255) NULL,
TenDangNhap NVARCHAR(255) NOT NULL,
MatKhau NVARCHAR(255) NOT NULL
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE HOADON(
ID INT IDENTITY(1,1) NOT NULL,
IDKhachHang INT NULL,
IDTinhTrang INT NULL,
IDNhanVien INT NULL,
NgayLap DATE NULL,
TongGia INT NULL,
NoiNhan NVARCHAR(255) NULL,
GhiChu TEXT
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE TABLE CHITIETHOADON(
ID INT IDENTITY(1,1) NOT NULL,
IDHoaDon INT NULL,
IDSanPham INT NULL,
IDPhuKien INT NULL,
SoLuongMua INT NULL,
DonGia INT NULL
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

Go
CREATE TABLE TINHTRANG(
ID INT IDENTITY(1,1) NOT NULL,
TinhTrang INT NULL
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE TABLE NHANVIEN(
ID INT IDENTITY(1,1) NOT NULL,
HoVaTen NVARCHAR(255) NOT NULL,
SoDienThoai INT NOT NULL,
Email NVARCHAR(255) NULL,
AnhDaiDien NVARCHAR(255) NULL,
TenDangNhap NVARCHAR(255) NOT NULL,
MatKhau NVARCHAR(255) NOT NULL,
Quyen INT NOT NULL
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--QUAN HỆ GIỮA CÁC BẢNG

ALTER TABLE [dbo].[SANPHAM]  WITH CHECK ADD FOREIGN KEY(IDNoiSanXuat)
REFERENCES [dbo].NOISANXUAT (ID)
GO

ALTER TABLE [dbo].[SANPHAM]  WITH CHECK ADD FOREIGN KEY(IDDongSanPham)
REFERENCES [dbo].DONGSANPHAM ([ID])
GO

ALTER TABLE [dbo].HOADON  WITH CHECK ADD FOREIGN KEY(IDKhachHang)
REFERENCES [dbo].KHACHHANG ([ID])
GO

ALTER TABLE [dbo].HOADON  WITH CHECK ADD FOREIGN KEY(IDNhanVien)
REFERENCES [dbo].NHANVIEN ([ID])
GO

ALTER TABLE [dbo].HOADON  WITH CHECK ADD FOREIGN KEY(IDTinhTrang)
REFERENCES [dbo].TINHTRANG ([ID])
GO

ALTER TABLE [dbo].CHITIETHOADON  WITH CHECK ADD FOREIGN KEY(IDSanPham)
REFERENCES [dbo].[SANPHAM] ([ID])
GO

ALTER TABLE [dbo].CHITIETHOADON  WITH CHECK ADD FOREIGN KEY(IDHoaDon)
REFERENCES [dbo].HOADON ([ID])
GO

ALTER TABLE [dbo].CHITIETHOADON  WITH CHECK ADD FOREIGN KEY(IDPhuKien)
REFERENCES [dbo].PHUKIEN ([ID])
GO

ALTER TABLE [dbo].KHUYENMAI  WITH CHECK ADD FOREIGN KEY(IDSanPam)
REFERENCES [dbo].[SANPHAM] ([ID])
GO

ALTER TABLE [dbo].KHUYENMAI  WITH CHECK ADD FOREIGN KEY(IDPhuKien)
REFERENCES [dbo].PHUKIEN ([ID])
GO

ALTER TABLE [dbo].DONGSANPHAM  WITH CHECK ADD FOREIGN KEY(IDDanhMuc)
REFERENCES [dbo].DANHMUCSANPHAM ([ID])
GO

ALTER TABLE [dbo].LOAIPHUKIEN  WITH CHECK ADD FOREIGN KEY(IDDanhMuc)
REFERENCES [dbo].DANHMUCSANPHAM ([ID])
GO

ALTER TABLE [dbo].PHUKIEN  WITH CHECK ADD FOREIGN KEY(IDLoaiPhuKien)
REFERENCES [dbo].LOAIPHUKIEN ([ID])
GO

ALTER TABLE [dbo].BINHLUAN  WITH CHECK ADD FOREIGN KEY(IDSanPham)
REFERENCES [dbo].[SANPHAM] ([ID])
GO

ALTER TABLE [dbo].BINHLUAN  WITH CHECK ADD FOREIGN KEY(IDPhuKien)
REFERENCES [dbo].PHUKIEN ([ID])
GO


ALTER TABLE KhachHang
ALTER COLUMN SoDienThoai NVARCHAR(255)
ALTER TABLE NhanVien
ALTER COLUMN SoDienThoai NVARCHAR(255)